### PR TITLE
Fix CSS for crypto header of inline composer

### PR DESCRIPTION
**Pull request by JocelynDelalande**
There was a CSS bug, the crypto header was floating around in the composer when
composing in the thread/inline view.

For the story, I had to PR #1682 and #1738 on the way to this tiny one-line PR :-)

Before:

screenshot-localhost 33411 2016-12-31 01-23-25

After:

screenshot-localhost 33411 2016-12-31 01-23-47

### CODE REVIEW

**Comment by BjarniRunar** [comment]
Thank you!

**Comment by loidor** [comment]
I'm curious about what browser this regards. I'm on Chrome and notices no difference at all in this regard. However, it messes with my inbox and subjects longer than 370px ends up wrapping and using more than one line.

If `white-space: nowrap;` needs to be excluded, would it be possible to only exclude it from `#pile-results td.subject` and still have it in `#pile-results td.subject a.item-subject`? That would make it possible to make subject lines end with ellipsis (...) if they're longer than 370px. 

Another way would to completely remove `width: 370px` from `#pile-results td.subject a.item-subject`, and it would wrap automatically if the subject line is longer than 100% of the div's estate.

**Comment by JocelynDelalande** [comment]
> I'm curious about what browser this regards. I'm on Chrome and notices no difference at all in this regard. However, it messes with my inbox and subjects longer than 370px ends up wrapping and using more than one line.

Oops. 

I'm using Firefox  45.

> If white-space: nowrap; needs to be excluded, would it be possible to only exclude it from #pile-results td.subject and still have it in #pile-results td.subject a.item-subject? That would make it possible to make subject lines end with ellipsis (...) if they're longer than 370px.

@loidor Would you PR this in a way that is ok for you ? I'd happily review & test it.

**Comment by loidor** [comment]
I'd love to! Just installed Firefox 45 and see the same problem, so that's good, I guess, since that gives me a testing platform :)

**Comment by JocelynDelalande** [comment]
@loidor Cool :) Don't forget to mention my on your PR so that I get notified :-)

**Pull request merged**
