### PR TITLE
#1911

### PR DESCRIPTION
**Pull request by dorumd**

### CODE REVIEW

**Comment by dorumd** [comment]
Fixes #1911

**Comment by BjarniRunar** [comment]
Thanks for this! At first glance, this looks great. I'm a bit overbusy at the moment so I'm not able to review this properly just yet, but I will as soon as I have a bit more time.

**Comment by dorumd** [comment]
@BjarniRunar Cool! If there is something else what I can help you with, let me know.

**Comment by BjarniRunar** [comment]
I've merged this in my local tree, should go live later today.

**Pull request merged**
