### PR TITLE
[WIP] Switch to less-elements-old

### PR DESCRIPTION
**Pull request by JocelynDelalande**
less-elements vanished from github ; and the [official site](http://lesselements.com/) does not even
mention a license. So, there is this *less-elements-old* fork remaining ; it's
not under active development (codebase is tiny) but at least it's online and
FLOSS :-)

Current PR is not sufficient, I am [waiting for a release of Rebar](https://github.com/bnvk/Rebar/pull/24#issuecomment-261797756) including the same patch, which also depends on less-elements old.

MP will need to depend on that new rebar.

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Rebar released https://github.com/bnvk/Rebar/pull/24#issuecomment-268667402 finally.

**Comment by BjarniRunar** [comment]
time to merge?

**Comment by JocelynDelalande** [comment]
No, wait a minute that I finish & test it.

**Comment by JocelynDelalande** [comment]
> time to merge?

@BjarniRunar Now yes :-)

**Pull request merged**
