### PR TITLE
[wip] alpine based Dockerfile

### PR DESCRIPTION
**Pull request by mathroc**
this is a work in progress

working:

* initialize a new mailpile environment
* adding account
* importing emails / contacts
* generating gpg key
* sending messages

image size is currently 101MB (vs 446MB before)

blocking issues:

*  accessing mailboxes (segmentation fault :/)
> Segmentation faultayed welcome message
mailpie_app_1 exited with code 139

I'm not sure how to find out what is causing the segmentation fault. If you have any suggestions, please let me know!
* unlocking pgp key (not sure which password it's asking for and what should happen when it's unlocked)
* signing outgoing messages (because I can't figure out how to unlock the key)
* encrypting outgoing message:
>   File "/Mailpile/mailpile/crypto/gpgi.py", line 442, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe

other issues:

* I don't know when this error appeared :
> Failed to load language C
Failed to configure i18n (C). Using fallback.

see #1698

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
Hi :)

I'm not even using docker but just wondering : is that a good move to switch onto an "exotic" (mind the quotes) system that is not mentioned in [install docs](https://github.com/mailpile/Mailpile/wiki/Getting-started-on-linux) for the default docker image ?

I mean, it adds maintenance (fixing depolyment/env bugs on alpine + ubuntu/debian), and means less testing on debian/ubuntu env (people using docker for dev will *not* test on deb/ubuntu).

As mailpile is intended for large audiences ; I'd prefer keeping the overweight of 300mio and having the default docker env remaining on Ubuntu. Again, that may be a naive opinion, because I'm no docker user…

**Comment by DoubleMalt** [comment]
Docker themselves announced a while ago the they intend to switch their
default images to alpine for the vast improvements of Docker image size.

While it doesn't seem to have hapened (yet), using ALpine for Docker images
is definietly not exotic any more.

**Comment by BjarniRunar** [comment]
Ping @DoubleMalt , @mathroc!

Should this be merged? I don't use docker myself so I don't know what to do with this issue; but I feel bad leaving it unmerged for months like this.

**Comment by mathroc** [comment]
I've rebased and updated the PR, everything seems to be working fine now

@grekko maybe you can test this too and if it's ok @BjarniRunar can merge it ?

**Comment by grekko** [comment]
@mathroc I tested some basic functionality w/ the Dockerfile and could succesfully:
- Start & configure mailpile
- Add an account & generate GPG keys
- Fetch E-Mails
- Send a signed/encrypted E-Mail

Besides these basic functionality tests I don't know that else to consider and would give a thumbs-up for the change 👍

**Comment by grekko** [comment]
@mathroc I had a second look at the packages you install and discovered that the original Dockerfile installs packes like `tor` and `spambayes` which are not explicitly mentioned in the new one.

**Comment by mathroc** [comment]
@grekko thank you for testing, I did not include `tor` because I think it should be run in a separate container. As for `spambayes` I don't remember why I did not install it; what is it used for ? and why is it not a dependency? (in requirements.txt)

anyone have thought about adding or not `tor` and `spambayes` ?

**Comment by grekko** [comment]
> I did not include tor because I think it should be run in a separate container.

Could you elaborate on that? Is that for security reasons? I guess this would require some adjustments on the Mailpile code. The docker orchestration part should be no problem with docker compose I guess.

> anyone have thought about adding or not tor and spambayes ?

I would argue to keep them for now since I assume they are required by Mailpile. Maybe @BjarniRunar has some thoughts on that.

**Comment by mathroc** [comment]
> Could you elaborate on that? Is that for security reasons? I guess this would require some adjustments on the Mailpile code. The docker orchestration part should be no problem with docker compose I guess.

first reason is that I'm used to have one container for one service, that way it's easier to let people use their own custom image of external services. for `tor`, while not that important, adding it in the Mailpile image would mean a larger image and a maintenance burden. but more importantly, users would probably thought that mailpile is "torified", but [the setup is much more complex](https://github.com/mailpile/Mailpile/wiki/Mail(pile)-TORified)

I don't think adjustments on the Mailpile code would be needed as using Mailpile with tor seems to be transparent to mailpile. it connect to an smtp port that is proxified by tor and the webui traffic comes from a tor but, afaik, Mailpile doesn't care about that either

providing an easy way to setup mailpile + tor could be interesting but I don't think it's a priority

**Comment by grekko** [comment]
> first reason is that I'm used to have one container for one service, that way it's easier to let people use their own custom image of external services.

To me the 1-service-per-container argument sounds a little too dogmatic in the case of Mailpile while I agree w/ the benefits of decoupled services generally.

My assumption was that enabling Tor-Support for Mailpile is a first-class feature and should work w/o any further tweaking by the user. If that is not the current reality but a short-term goal I would vote for inlcuding it in the Dockerfile.

If Tor-Support is not really that important it could probably be also excluded. While I am pretty new to the project and cannot tell much about the importance of Tor-Support probably @BjarniRunar can.

**Comment by BjarniRunar** [comment]
Hello!

Without spambayes you have no spam protection, so although the app will run without it, it is pretty important. It is in requirements.txt, but if the operating system provides a package it makes sense to use that IMO.

Tor is optional, but many of the privacy features Mailpile wants to offer depend on it being present, and that is going to increase over time. If it can be included in the default Dockerfile that seems to me like the right thing to do; folks that don't want it for some reason can fork the file, no?

**Comment by BjarniRunar** [comment]
Another point regarding Tor - future versions of Mailpile will be creating and exposing hidden services. I don't know if this is even possible for Mailpile to do if Tor itself is in a different container. And for context, when we build Mac and Windows packages, I do hope we will be able to bundle Tor, for the same reasons.

**Comment by mathroc** [comment]
thank you for the input @BjarniRunar 

alpine does not have its own spambayes package but it should be installed by pip

I can install tor inside the image right now but it will be much more work to start it along with mailpile. the current ubuntu image does not start it either. It'll mean adding a supervisor such as [s6](https://github.com/just-containers/s6-overlay) to start mailpile, tor & dnsmasq + adding whatever is necessary to configure all this through environement variables

I'd rather add tor in a following PR if that's okay (or only install it if it's useful on its own) as I'll have to learn more about tor before being able to add that

**Comment by BjarniRunar** [comment]
Cool! As an aside, this may in fact be a weak argument for using a slightly larger image than Alpine; something Debian based will already have Tor packages that just work. Having a small image is nice, but if it means we have to reinvent too many wheels it may not be worth it.

**Comment by mathroc** [comment]
well with a debian image you will also have to configure a supervisor. as most images, debian images does not start a initd/supervisor by default (it only starts bash) and it's not really possible/easier to use the same as a "full" debian system (systemd) inside an image as the configuration would be very different (no need to mount filesystems /sys/… start networks, tty, etc.)

it's not really starting multiple processes that will slow me down (it will only take a bit of time) it's mainly that I have close to no experience with tor :)

**Comment by grekko** [comment]
@mathroc Ah, now I see what you are referring too. Having tor in the image is only useful if its run when starting the docker container, but currently we just run the mailpile service anyways.

When you mention the supervisor you are referring to the [PID 1 Problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/), are you?

In any case: If the current/previous dockerized Mailpile solution does not support running the Tor-Service it might make sense to not install the package.

Instead there should be an Issue/Chore that targets extending the the dockerized version of Mailpile to properly run Tor in another container and hook it up w/ the mailpile service. What do you think?

**Comment by mathroc** [comment]
> When you mention the supervisor you are referring to the PID 1 Problem, are you?

yep, well, not exactly the same problem but it's closely related. I don't think mailpile itself produces zombie so I didn't add an init (eg: [tini](https://github.com/krallin/tini) but if we want to start multiple processes, we have to introduce a parent to those processed to not let them run headless (and handle restarting or stopping them when appropriate)

> Instead there should be an Issue/Chore that targets extending the the dockerized version of Mailpile to properly run Tor in another container and hook it up w/ the mailpile service. What do you think?

👍 we'll have to look if it's possible to have tor in a separate container. and even if it is, we might want to first run it in the same image for easier deployment (maybe with the option of using an external tor for advanced used)

**Comment by BjarniRunar** [comment]
I'm going to close this in favour of #1804, which AFAICT has incorporated most of these changes and more. Thanks everyone who chimed in, and especially @mathroc for getting the ball rolling.

**Pull request closed without merging**
