### PR TITLE
Added less-elements dependency to repository

### PR DESCRIPTION
**Pull request by broder**
https://github.com/dmitryf/elements seems to have been removed so I've added the .less file to the repository.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
What do you think @JocelynDelalande , is this better or worse than what your stalled solution? :)

**Comment by JocelynDelalande** [comment]
@broder does it fix the issue with rebar too ?

**Comment by JocelynDelalande** [comment]
@broder FYI, @BjarniRunar is refering to #1682 

> @broder does it fix the issue with rebar too ?

Auto-replying : yes, it does, that's what the igoreDependencies is for.

Ok for me then ; I'm not a big fan, but let's face it, we are stuck and front-end is unbuildable as is, so thanks @broder for that pragmatic fix.

@broder maybe

**Comment by JocelynDelalande** [comment]
Ah, it moved on rebar side ! https://github.com/bnvk/Rebar/pull/24#issuecomment-268667402 So i'd suggest keeping the simpler path taken via #1682 for the moment

**Comment by broder** [comment]
:+1:

**Comment by JocelynDelalande** [comment]
@broder thanks for your contribution anyway, and sorry for your time wasted.

**Pull request closed without merging**
