### PR TITLE
RFC 2606 compliance, bug #1315

### PR DESCRIPTION
**Pull request by nathans**
This should cover my bug regarding the use of "example.com" in the product.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
I understand the sentiment, but if we're going to pick nits... well your replacements are too long! :-) They're not fully visible because the input field is too small.

Without resizing the input fields, we can choose between RFC compliance or Chelsea, we can't really have both. I think I'd rather make the political statement than comply with the RFC, but I'm quite willing to hear arguments either way.

**Comment by DoubleMalt** [comment]
+1 for political statement and humor. I think at this stage of the project
these things should take precedence over pedantic RFC compliance.

**Comment by bnvk** [comment]
@nathans thanks for the contribution + suggestion. However, I tend to agree with @BjarniRunar @DoubleMalt and like having a little bit of political fun with our naming as well.

**Comment by BjarniRunar** [comment]
I think the question is: do any other similar political references fit in the box and end in @example.com ?

**Comment by bnvk** [comment]
To that end, we could do `c.manning@example.com` or `chelsea.m@example.com` not sure if those fit in the fields or not, but maybe!

**Comment by nathans** [comment]
I'll go ahead and close this pull request since it won't be merged at any rate. You can take or leave the suggestion, and I can even make a fresh pull request if desired. Just comment on the issue I opened if that is desired. Thanks.

**Comment by BjarniRunar** [comment]
Thanks @nathans !

**Pull request closed without merging**
