### PR TITLE
Add the mp script to the python setup

### LINKED ISSUE #1660: Missing mp script in python setup
The python scripts section of the setup.py is used to indicate the scripts that will be installed in the system.

Right now, if I setup my virtualenv in the mailpile repository directory and try to do pip install ., I won't be able to just call mp because it won't be installed.

```
elopio@remote-devel:~/workspace/mailpile/Mailpile> virtualenv -p /usr/bin/python2.7 --system-site-packages mp-virtualenv
elopio@remote-devel:~/workspace/mailpile/Mailpile> source mp-virtualenv/bin/activate
(mp-virtualenv) elopio@remote-devel:~/workspace/mailpile/Mailpile> pip install -r requirements-dev.txt
(mp-virtualenv) elopio@remote-devel:~/workspace/mailpile/Mailpile> pip install .
(mp-virtualenv) elopio@remote-devel:~/workspace/mailpile/Mailpile> mp
mp: command not found
```

### PR DESCRIPTION
**Pull request by elopio**
Closes #1660

### CODE REVIEW

**Comment by elopio** [comment]
```
(mp-virtualenv) elopio@remote-devel:~/workspace/mailpile/Mailpile> pip install .
(mp-virtualenv) elopio@remote-devel:~/workspace/mailpile/Mailpile> mp
Metadata index not found: /home/elopio/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.050s (Loaded metadata, 0 messages)                                  
Metadata index not found: /home/elopio/.local/share/Mailpile/default/mailpile.idx
Elapsed: 0.002s (load: Loaded metadata index)
Elapsed: 0.001s (motd: )
Mailpile.py              a tool             Copyright 2013-2016, Mailpile ehf
 v1.0.0rc0         for searching and               <https://www.mailpile.is/>
               organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>



mailpile>
```

**Comment by BjarniRunar** [comment]
Doesn't this make "mp" go into /usr/bin (or equivalent) if this is installed using pip install or as the basis for a .deb/.rpm package?

If yes, I think it should be installed as "mailpile", not "mp".

However, I wonder if that's already being done by the build_py. There's some magic going on in there and I'd rather we don't break it! Perhaps @aviau can comment on this?

**Comment by elopio** [comment]
Yes, it goes to the bin directory. I've just changed it to be mailpile instead of mp.
I took a look at the make file called by build_py, and it's a little scary, so I'll just wait for @aviau's comment too :)

**Comment by elopio** [comment]
Ping. No news on this?

**Comment by aviau** [comment]
This isn't needed, it would be a duplicate of what the setup.cfg already does.

```bash
$ virtualenv env
$ source env/bin/activate
$ pip install -r requirements.txt
$ python setup.py install
$ mailpile
```

**Comment by BjarniRunar** [comment]
Does this mean we have a bug here, in that it didn't do what was expected, or are our docs out-of-date/incorrect?

**Comment by aviau** [comment]
Update: I have tried installing it with pip, and it worked. Most likely you forgot a dependency?

```bash
$ virtualenv env
$ source env/bin/activate
$ pip install -r requirements.txt
$ pip install .
$ which mailpile
/home/aviau/git/Mailpile/env/bin/mailpile
```

**Comment by aviau** [comment]
> Does this mean we have a bug here

As shown above, there is no bug.

> are our docs out-of-date/incorrect

They are not. Actually, we don't even recommend installing the package itself in a virtual environment in the docs. Instead, we recommend installing the dependencies and running Mailpile from the source. But anyways, we still support running Mailpile in every immaginable way and I [remember](https://github.com/mailpile/Mailpile/commit/1bf62d54133fb80f374c2fd4206dad5049acff88) working [hard](https://github.com/mailpile/Mailpile/commit/6d57b5de7830f2d4f9bf95c8cf05f8773d2f61da) to make sure that it works in all setups.

**Comment by elopio** [comment]
nop, I understand now. I was looking for a binary called mp, not for one called mailpile. A little dump of my part.
I'm sorry for wasting your time, but thanks for helping me understand my issue. I'll close the bug and the pr.

**Comment by BjarniRunar** [comment]
Thanks both of you!

**Pull request closed without merging**
