### PR TITLE
Support for bare PGP-encrypted attachments; see issues #1004, #701

### PR DESCRIPTION
**Pull request by JackDca**

### CODE REVIEW

**Comment by JackDca** [comment]
Each MIME part with content-disposition "attachment" is sniffed to see if they are PGP objects.  If so, it is unwrapped, then the process is repeated on the contents.  The PGP data is used to restore the original file name - if it is absent, the "filename" field from content-disposition is used, trimming off ".asc" or ".pgp" as appropriate.  Possible enhancments:  There may be performance issues due to the way gpg --list-packets is used to do the sniffing.  Also, it may be better to avoid sniffing some content-types.

**Comment by BjarniRunar** [comment]
Thank you for doing this! Copy-pasting my comments from IRC:

Hmm, could you not use the Python pgpdump instead with in-memory data, to avoid having to invoke gpg on every single attachment? Seems this will slow down everything, all the time, which isn't a good direction for things. I'd only sniff if it's an attachment of  a type we either recognize as encrypted, or don't recognize at all.

If we recognize the mime-type of an attachment as *not* being something encrypted, then we could skip the sniff. :)  This'll take some iteration most likely.

There is some sample code in the plugins/keydiscovery code, we use it to find keys.

**Comment by JackDca** [comment]
To address possible performance issues, in this version GnuPG.sniff() does not use gpg or pgpdump.  It accepts base64, quoted-printable or unencoded data.  Encoded data is decoded in segments only as required.  PGP objects that are armored (before encoding) are recognized from the armor header only.  Non-armored objects are recognized by decoding the PGP packet headers only and checking them for legality.

**Comment by JackDca** [comment]
Most testing of this code has been done using the JackDca/Mailpile bare-pgp-attachments branch which is based on the GitHub Mailpile master code from 2015-10-21.   Additional testing has also been done by merging bare-pgp-attachments into the GitHub Mailpile master code from 2016-02-04.  That merged code is now on JackDca/Mailpile master.

**Comment by BjarniRunar** [comment]
I have merged this into my local branch - am performing a few more tests and cleaning up some other things before I push. Thank you for doing this!

**Comment by JackDca** [comment]
Thank you for your work on Mailpile!  Let me know of any problems or suggestions.  I am ready to do more work on this code if you decide it's needed.

**Comment by JackDca** [comment]
One-line fixes to attachments handling.

The maximum base64 line length per RFC2045 6.8 is 76 characters.  This does NOT include the white space at the end of line.  Discovered this when processing an email from an outlook.com mail box.  Looks like outlook.com modifies base64 encoding by changing the division into lines so the lines are the maximum 76 length. (gpgi.py sniff()).

Catch IndexError exceptions in pgpdump.  A corrupt large attachment (armored with the last part including the -----END PGP ... cut off) caused an IndexError in pgpdump with the result that the incoming email was discarded completely.  Preferably this should be fixed upstream in pgpdump but catching the exception fixes it. (email_keylookup.py _get_keydata() )

**Pull request merged**
