### PR TITLE
remove some minified js libs

### PR DESCRIPTION
**Pull request by aviau**
this is part of #1465

This removes some embedded minified js libs, which will be minified at build time instead.

I'll come up with a solution for libraries.js in another PR.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
I'm going to hold off on this for a bit; changing this means we also need to update our installation procedures, which assume the compiled files are checked in and folks don't need a build step after git pull.

**Comment by aviau** [comment]
I am willing to update the docs.

Is there anything else than https://github.com/mailpile/Mailpile/wiki/Getting-started and its sub-pages?

**Comment by BjarniRunar** [comment]
Dragging my feet a bit.. is it possible to exclude the minified JS from the tarball you build, instead of removing it from git and adding to .gitignore?

I like the other changes you've made (and would like to merge them!), but I am quite fond of the fact that folks can git pull and then just run the app, without installing a whole bunch of dev tools.

**Comment by aviau** [comment]
Fair enough. I'll even allow you to include it in the tarball and I'll exclude it from the tarball when downloading it. This way we get the best of both worlds - minified js for those that want it and souce for the others.

**Pull request merged**
