### PR TITLE
Clarify that "Download all mail" will leave mail on the server

### PR DESCRIPTION
**Pull request by tuxlifan**
possible solution for #1612

### CODE REVIEW

**Comment by BjarniRunar** [comment]
How about we just use the word Copy instead of Download? :-)

Making the string 2x as long isn't great for translations or layout, and generally the fewer words the better from a usability pov. Most people don't read good...

**Comment by JocelynDelalande** [comment]
@tuxlifan bump on that ?

**Comment by JocelynDelalande** [comment]
I agree with @BjarniRunar suggestion.

**Comment by tuxlifan** [comment]
Yes, "Copy" sounds like a great solution! (Sorry, been offline for a while.)

**Comment by BjarniRunar** [comment]
Thank you!

**Pull request merged**
