### PR TITLE
Save the metadata index more often

### PR DESCRIPTION
**Pull request by JackDca**
To reduce vulnerability to unclean shutdowns (#2044):
- Saves to `mailpile.idx` are done every 15 minutes by a cron task if there is any change to save. This is in addition to the saves previously implemented in the code, which are triggered by message tagging and similar events.
- Most saves are appends, not full rewrites.
- A full rewrite is performed if the total number of appends to the file exceeds 1/200 of the number of lines in the file (minimum 5000/200 = 25).
- A full rewrite of the file is performed if the number of duplicated lines in the file exceeds 1/10 of the number of lines in the file (minimum 5000/10 = 500). Duplicated lines are those which repeat a previous `MSG_MID` (for message entries) or Contact Index ID (for contact entries).
- Notwithstanding the above, a full rewrite is **never** performed when Mailpile is shutting down.
- Each append is introduced by a blank line (`"\n"`) in the plaintext `mailpile.idx`.
- When loading the file at Mailpile startup, the number of appends already in the file is initialized by counting blank lines, then that number is incremented whenever a new append is made.
- When loading the file at Mailpile startup, the number of lines already in the file is counted, then that count is updated whenever a new append is done. The difference between the number of lines in the file, and the combined number of items in the internal `INDEX` and `EMAILS` lists, is the number of duplicated lines.

The code was tested on a sample IMAP account with about 250 messages and on a production Mailpile instance with 50,000 messages by changing the parameter values (200, 10, 5000) that control full rewrites to exercise all parts of the new code.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
Cool, thanks for doing this!

I mostly like this approach, except for the blank-lines-with-meaning hack. That feels brittle to me. How about, on load, comparing a) how many lines were actually read from the file with b) how large the index really is (`len(self.INDEX)`) - that gives you a ratio that tells you roughly the same thing? It doesn't matter if the number is 100% accurate or not, it just needs to be "good enough" to prevent runaway index bloat.

OTOH - I *really* like your change to prevent a full rewrite on shutdown, that's a major improvement!

**Comment by JackDca** [comment]
This PR already calculates a (total lines) - (`len(self.INDEX)`) difference ("duplicate" line count) and puts a limit on it. Problem is, if one email arrives in one 15 minute interval, it generates one append,  one new line and one INDEX entry. This leaves the "duplicate" count unchanged. Yet the execution time overhead to write/read one append is on the order of 20x the time required to write one line (see results and rationale in latest comments in #2044).

I could get rid of  the blank lines and the explicit append count, while lowering the permitted "duplicate" lines to 1% of total lines from the present 10%. In _normal_ use, each incoming email will eventually be read, trashed, and/or tagged, which _will_ create a "duplicate" line (and also another append!). So in _normal_ use the limit on the "duplicate" count will also roughly limit the number  of appends in the file.

The fragility you reference is as you explained in #1566, that is a future contributor might not be aware of that detail of the file format. One way to address that is by documentation, both internal and external. See [Data formats - Metadata index](https://github.com/mailpile/Mailpile/wiki/Data-formats:-Metadata-index) . My concern is code that is fragile in another way, i.e. it works well under _normal_  use but not so well in the edge cases. I like rigor.

In any case, I'll modify the PR as per your request. I should get to it on Monday.

**Comment by JackDca** [comment]
@BjarniRunar - after letting this simmer for a while, I am not satisfied with the heuristic approach of limiting the number of duplicate lines in the `mailpile.idx` file without explicitly limiting the number of appends. Reducing the limit on duplicate lines to 1% will increase the number of complete rewrites unnecessarily. Agreed, the use of a blank line to mark the start of an append was a bit too clever and not obvious to the reader. So I'd like to mark the start of an append with `#-----APPENDED SECTION-----\n`.

The code has always recognized lines starting with # as comments so this change is backward compatible.  It affects the way the program handles the file without affecting the information content of the file; this is consistent with other use of comments to encode metadata e.g. hash-bang #! at the start of scripts which is not part of the script itself but helps the OS handle it; similar stuff is done in HTML.

If you can accept this approach I'll update the PR.

**Comment by BjarniRunar** [comment]
Go for it. :+1:

**Comment by JackDca** [comment]
Done.

This was tested thoroughly when the append marker was a blank line (see above). Just to be sure, accelerated testing was done on this commit by modifying the mailpile.idx write interval to 300 s from 900 s and ITEM_COUNT_OFFSET to 250 from 5000 for the duration of the test.

**Comment by BjarniRunar** [comment]
Thanks! Merging this in my local tree so I can kick the tires a bit before pushing.

**Pull request merged**
