### PR TITLE
Small fixes on dev env

### PR DESCRIPTION
**Pull request by JocelynDelalande**
Easy one :-)

### CODE REVIEW

**Comment by BjarniRunar** [comment]
Now we have pycrypto twice. ;-)

**Comment by JocelynDelalande** [comment]
What do you mean ?

**Comment by JackDca** [comment]
I can't check out the current master and set up a development environment on my Debian Jessie system using the procedure that has worked in the past.

When I clone the current master 6f56fe4 then
virtualenv -p /usr/bin/python2.7 --system-site-packages mp-virtualenv
source mp-virtualenv/bin/activate
pip install -r requirements-dev.txt

the last command fails, telling me that pycrypto appears twice in requirements.dev.txt.

But if I delete the second reference to pycrypto (the last line of requirements-dev.txt) and start all over again I get a lot or errors.  I've copied the console output below.  Any suggestions would be welcome.

jack@Lucy2:~/Desktop/MPJack/Code$ git clone https://github.com/mailpile/Mailpile Temp
Cloning into 'Temp'...
remote: Counting objects: 39680, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 39680 (delta 18), reused 0 (delta 0), pack-reused 39632
Receiving objects: 100% (39680/39680), 20.22 MiB | 1018.00 KiB/s, done.
Resolving deltas: 100% (26879/26879), done.
Checking connectivity... done.
jack@Lucy2:~/Desktop/MPJack/Code$ cd Temp
jack@Lucy2:~/Desktop/MPJack/Code/Temp$ # Delete second ref to pycrypto
jack@Lucy2:~/Desktop/MPJack/Code/Temp$ nano requirements-dev.txt
jack@Lucy2:~/Desktop/MPJack/Code/Temp$ virtualenv -p /usr/bin/python2.7 --system-site-packages mp-virtualenv
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in mp-virtualenv/bin/python2.7
Also creating executable in mp-virtualenv/bin/python
Installing setuptools, pip...done.
jack@Lucy2:~/Desktop/MPJack/Code/Temp$ source mp-virtualenv/bin/activate
(mp-virtualenv)jack@Lucy2:~/Desktop/MPJack/Code/Temp$ pip install -r requirements-dev.txt
Downloading/unpacking appdirs (from -r requirements-dev.txt (line 1))
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking setuptools>=11.3 (from -r requirements-dev.txt (line 2))
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB): 390kB downloaded
Downloading/unpacking cryptography>=1.3.4 (from -r requirements-dev.txt (line 3))
  Downloading cryptography-1.8.1.tar.gz (423kB): 423kB downloaded
  Running setup.py (path:/tmp/pip-build-doaohw/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.3.2 in /usr/lib/python2.7/dist-packages (from -r requirements-dev.txt (line 4))
Downloading/unpacking Jinja2 (from -r requirements-dev.txt (line 5))
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB): 340kB downloaded
Downloading/unpacking spambayes>=1.1b1 (from -r requirements-dev.txt (line 6))
  Downloading spambayes-1.1b2.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py (path:/tmp/pip-build-doaohw/spambayes/setup.py) egg_info for package spambayes
    
Downloading/unpacking selenium>=2.40.0 (from -r requirements-dev.txt (line 7))
  Downloading selenium-3.4.1-py2.py3-none-any.whl (931kB): 931kB downloaded
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python2.7/dist-packages (from -r requirements-dev.txt (line 8))
Downloading/unpacking nose (from -r requirements-dev.txt (line 9))
  Downloading nose-1.3.7-py2-none-any.whl (154kB): 154kB downloaded
Downloading/unpacking mock>=1.0.1 (from -r requirements-dev.txt (line 10))
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements-dev.txt (line 11))
Downloading/unpacking pyDNS (from -r requirements-dev.txt (line 12))
  Downloading pydns-2.3.6.tar.gz
  Running setup.py (path:/tmp/pip-build-doaohw/pyDNS/setup.py) egg_info for package pyDNS
    
Downloading/unpacking pgpdump (from -r requirements-dev.txt (line 13))
  Downloading pgpdump-1.5.tar.gz (69kB): 69kB downloaded
  Running setup.py (path:/tmp/pip-build-doaohw/pgpdump/setup.py) egg_info for package pgpdump
    
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/lib/python2.7/dist-packages (from -r requirements-dev.txt (line 14))
Downloading/unpacking pbr (from -r requirements-dev.txt (line 15))
  Downloading pbr-3.0.0-py2.py3-none-any.whl (98kB): 98kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.0 in /usr/lib/python2.7/dist-packages (from setuptools>=11.3->-r requirements-dev.txt (line 2))
Downloading/unpacking packaging>=16.8 (from setuptools>=11.3->-r requirements-dev.txt (line 2))
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking idna>=2.1 (from cryptography>=1.3.4->-r requirements-dev.txt (line 3))
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking asn1crypto>=0.21.0 (from cryptography>=1.3.4->-r requirements-dev.txt (line 3))
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB): 97kB downloaded
Downloading/unpacking enum34 (from cryptography>=1.3.4->-r requirements-dev.txt (line 3))
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking ipaddress (from cryptography>=1.3.4->-r requirements-dev.txt (line 3))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.3.4->-r requirements-dev.txt (line 3))
  Downloading cffi-1.10.0.tar.gz (418kB): 418kB downloaded
  Running setup.py (path:/tmp/pip-build-doaohw/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking lockfile>=0.2 (from spambayes>=1.1b1->-r requirements-dev.txt (line 6))
  Downloading lockfile-0.12.2-py2.py3-none-any.whl
Downloading/unpacking funcsigs>=1 (from mock>=1.0.1->-r requirements-dev.txt (line 10))
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=11.3->-r requirements-dev.txt (line 2))
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.3.4->-r requirements-dev.txt (line 3))
Installing collected packages: appdirs, setuptools, cryptography, Jinja2, spambayes, selenium, nose, mock, pyDNS, pgpdump, pbr, packaging, idna, asn1crypto, enum34, ipaddress, cffi, lockfile, funcsigs, pyparsing
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Found existing installation: cryptography 0.6.1
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, outside environment /home/jack/Projects/MPJack/Code/Temp/mp-virtualenv
  Running setup.py install for cryptography
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command /home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-doaohw/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fj2fZX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-doaohw/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fj2fZX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jack/Projects/MPJack/Code/Temp/mp-virtualenv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-doaohw/cryptography
Storing debug log for failure in /home/jack/.pip/pip.log
(mp-virtualenv)jack@Lucy2:~/Desktop/MPJack/Code/Temp$

**Comment by BjarniRunar** [comment]
Argh, having it twice is a problem? That's... a surprise. I'll push up a fix as soon as I have a moment. Nto sure about the rest of that, I can't look closely right now. But thank you for reporting it @JackDca.

**Comment by JackDca** [comment]
See #1839 for a possible fix.

**Comment by JackDca** [comment]
Upgrading to Debian stretch - the new stable - fixes this as described in #1839.

(This includes the complaint about the duplication of pycrypto in requirements-dev.txt.)

**Pull request merged**
