### PR TITLE
Improved Dockerfile

### PR DESCRIPTION
**Pull request by dbrgn**
- Comments
- .dockerignore
- Added spambayes dependency
- Fig is now docker-compose
- Volume mapping is not really necessary in docker-compose.yml

### CODE REVIEW

**Comment by DoubleMalt** [comment]
I'm not sure about the change in the docker-compose file. Mailpile does not pick up changes in the python code.
It would help for tinkering with the frontend code, though. Maybe add this as comment.

**Comment by dbrgn** [comment]
Well, it depends whether the Dockerfile should primarily be used for dev or for deployment. I think the latter should be the target. For development, people can create their own volume mappings.

**Comment by DoubleMalt** [comment]
If the latter is the target, the volume is unnecessary, as the ADD command already adds the files to the image on build.

**Comment by dbrgn** [comment]
Exactly.

**Comment by DoubleMalt** [comment]
Ok, my bad. Somehow thought you had added the volume.

Maybe add a docker-compose.dev.yml. But that does not concern this pull request, that I wholeheartedly support.

**Comment by dbrgn** [comment]
Right now the docker-compose file is not really needed anyways. It only makes sense when running and linking multiple containers.

It does the port mapping for you though, so I think we can keep it.

**Comment by DoubleMalt** [comment]
lgtm

**Comment by DoubleMalt** [comment]
:+1:

**Pull request merged**
